### Sessionストア：Redisの設定
spring.session.store-type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=5000

### HTTPリクエストのヘッダー転送設定（AWSでのALB使用時）
server.forward-headers-strategy=native
